[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "example"
path = "./bin/example.rs"

[dependencies]
tokio = { version = "1.18.2", features = ["rt"]}
